load_applet_training <- function() {
  t <- read.csv("data/derived/filtered_training.csv", stringsAsFactors=FALSE)
  labels <- c(hmp_ec_stool="Stool EC", hmp_tax_stool="Stool SGB", hmp_tax_oral="Oral SGB", hmp_tax_skin="Skin SGB", hmp_tax_vaginal="Vaginal SGB")
  t <- t[match(names(labels),t$id),]
  data.frame(dataset=t$dataset,feature_class="Retained",samples=t$samples,
    total_features=t$retained_features,class_features=t$retained_features,
    input_features=t$observed_features,sd_25=t$sd_25,sd_50=t$sd_50,sd_75=t$sd_75,
    key=unname(labels),excluded=t$excluded_observed_features,
    definition=sprintf("Of %d detected features, %d were retained using %s. These filters reduce the feature set for linear modeling. Excluded features are omitted from the SD distribution and default testing family.", t$observed_features,t$retained_features, ifelse(t$feature_type=="EC", "detection in ≥80% of samples, with no abundance threshold", "prevalence ≥10% and mean relative abundance >0.01% among positive samples")))
}

training_grant_intro <- function(t) {
  stopifnot(nrow(t)==1)
  ec <- grepl('ECs',t$dataset,fixed=TRUE)
  site <- sub('HMP1-2 taxonomy ', '', t$dataset, fixed=TRUE)
  if(ec)site <- 'stool'
  profile <- if(ec)'unstratified enzyme commission (EC) profiles' else 'taxonomic profiles'
  profiler <- if(ec)'HUMAnN 4' else 'MetaPhlAn 4.0.6'
  opening <- sprintf('Variance within %s was estimated from %d %s metagenomes generated by the HMP1-II Project (Lloyd-Price et al., 2017; PMID: 28953883), profiled with %s.',profile,t$samples,site,profiler)
  filter <- if(ec)sprintf('To reduce data dimensionality for downstream linear modeling, %d detected unstratified EC features were filtered to retain features detected in at least 80%% of samples, retaining %d features. No mean-abundance filter was applied.',t$input_features,t$class_features) else sprintf('To reduce data dimensionality for downstream linear modeling, %d detected features were filtered to retain features with at least 10%% prevalence and >0.01%% mean relative abundance among positive samples, retaining %d features.',t$input_features,t$class_features)
  qs <- paste(sprintf('%.5g',as.numeric(t[1,c('sd_25','sd_50','sd_75')])),collapse=', ')
  paste(opening,filter,'Excluded features are omitted from the SD distribution and default testing family.',sprintf('The 25th, 50th, and 75th percentiles of retained feature SDs were %s on the arcsine-square-root relative-abundance scale, calculated among positive samples.',qs))
}
